name: Ansible

on:
  push:
    branches: [ main, master, develop ]
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible.yml'
  pull_request:
    branches: [ main, master, develop ]
    paths:
      - 'ansible/**'
      - '.github/workflows/ansible.yml'
  workflow_dispatch:

jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible ansible-lint yamllint

      - name: Run yamllint
        run: yamllint roles/web  

      - name: Run ansible-lint
        run: ansible-lint playbooks/site.yml roles/
        
      - name: Validate Ansible syntax
        working-directory: ansible
        run: ansible-playbook --syntax-check playbooks/site.yml -i inventory/containers.ini

  molecule-test:
    name: Molecule Test
    runs-on: ubuntu-latest
    needs: ansible-lint
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-plugins[docker] ansible-lint pytest-testinfra

      - name: Run Molecule tests
        run: molecule test
        working-directory: ./ansible/roles/web
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'

